// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSZl0g2CcrU1HnX9NLTnoe2CM2LxkCGo',
    appId: '1:89767305458:web:397185ee583ae62d27706b',
    messagingSenderId: '89767305458',
    projectId: 'remote-controller-93f07',
    authDomain: 'remote-controller-93f07.firebaseapp.com',
    databaseURL: 'https://remote-controller-93f07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remote-controller-93f07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzBqvKxvy52N7LBamHT8Wz52PChePRTHQ',
    appId: '1:89767305458:android:3520effc35796c2727706b',
    messagingSenderId: '89767305458',
    projectId: 'remote-controller-93f07',
    databaseURL: 'https://remote-controller-93f07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'remote-controller-93f07.firebasestorage.app',
  );
}
